require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.colorscheme')
require('user.cmp')
require('user.lsp')
require('user.telescope')
require('user.treesitter')
require('user.autopairs')
require('user.comment')
require('user.gitsigns')
require('user.nvim-tree')
require('user.bufferline')
require('user.lualine')
require('user.project')
require('user.impatient')
require('user.indentline')
require('user.alpha')
require('user.whichkey')
require('user.autocommands')
require('user.smoothscroll')
require('user.dap')
require('user.dressing')
require('user.autosession')
require('user.cheatsheet')
require('user.mini')
-- require('user.scroll')
-- require('user.toggleterm')
